# Generated by Django 5.1.2 on 2024-11-14 18:59

import django.db.models.deletion
import drt.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('negotiation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requestor_responses', models.JSONField(blank=True, null=True)),
                ('owner_responses', models.JSONField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('requestor_open', 'Requestor Open'), ('owner_open', 'Owner Open'), ('completed', 'Completed'), ('archived', 'Archived'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='requestor_open', max_length=50)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('questionnaire_SAID', models.CharField(max_length=255)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('requestor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requestor_email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_timestamp', models.DateTimeField(auto_now_add=True)),
                ('archived_data', models.JSONField()),
                ('negotiation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation')),
            ],
        ),
        migrations.CreateModel(
            name='NLink',
            fields=[
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('license_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('requestor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requestor_link', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('owner_link', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expiration_date', models.DateTimeField(default=drt.models.default_expiration_date)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('negotiation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateTimeField(auto_now_add=True)),
                ('datasets_requested', models.JSONField()),
                ('overall_stat', models.JSONField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.nlink')),
            ],
        ),
    ]
