# Generated by Django 5.1.2 on 2024-10-16 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('negotiation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestor_responses', models.JSONField()),
                ('owner_responses', models.JSONField()),
                ('negotiation_status', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('requestor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestor_email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expiray', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archived_timestamp', models.DateTimeField(auto_now_add=True)),
                ('archived_data', models.JSONField()),
                ('negotiation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaire_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('schema', models.JSONField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('saved_data', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.owner')),
            ],
        ),
        migrations.AddField(
            model_name='negotiation',
            name='questionnaire_SAID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.questionnaire'),
        ),
        migrations.CreateModel(
            name='NLink',
            fields=[
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('negotiation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.owner')),
                ('questionnaire_SAID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.questionnaire')),
                ('requestor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.requestor')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_date', models.DateTimeField(auto_now_add=True)),
                ('datasets_requested', models.JSONField()),
                ('overall_stat', models.JSONField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.owner')),
            ],
        ),
    ]
