# Generated by Django 5.1.2 on 2024-10-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0002_alter_requestor_requestor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlink',
            name='negotiation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation'),
        ),
    ]
