# Generated by Django 5.1.2 on 2025-05-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0002_archive_questionnaire_said'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystatistic',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='summary_statistics', to='drt.nlink'),
        ),
    ]
