# Generated by Django 5.1.2 on 2024-10-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0003_alter_nlink_negotiation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlink',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drt.owner'),
        ),
        migrations.AlterField(
            model_name='nlink',
            name='questionnaire_SAID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drt.questionnaire'),
        ),
    ]
