# Generated by Django 5.1.2 on 2024-10-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0004_alter_nlink_owner_id_alter_nlink_questionnaire_said'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystatistics',
            name='owner_id',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='owner',
        ),
        migrations.AlterField(
            model_name='nlink',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='questionnaire_SAID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nlink',
            name='questionnaire_SAID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
