# Generated by Django 5.1.2 on 2024-10-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0005_alter_summarystatistics_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlink',
            name='requestor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drt.requestor'),
        ),
    ]
