# Generated by Django 5.1.2 on 2024-10-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0006_alter_nlink_requestor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestor',
            old_name='otp_expiray',
            new_name='otp_expiry',
        ),
    ]
