# Generated by Django 5.1.2 on 2024-10-17 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0007_rename_otp_expiray_requestor_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlink',
            name='requestor_id',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='state',
            field=models.CharField(default='requestor_open', max_length=50),
        ),
        migrations.AddField(
            model_name='nlink',
            name='dataset_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nlink',
            name='owner_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='nlink',
            name='requestor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nlink',
            name='requestor_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='nlink',
            name='state',
            field=models.CharField(default='requestor_open', max_length=50),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='negotiation_status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='nlink',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
