# Generated by Django 5.1.2 on 2024-10-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0008_remove_nlink_requestor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlink',
            name='license_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
