# Generated by Django 5.1.2 on 2024-10-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0009_nlink_license_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlink',
            name='data_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
