# Generated by Django 5.1.2 on 2025-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0009_nlink_record_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarystatistic',
            name='record_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
