# Generated by Django 5.1.2 on 2024-10-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0010_nlink_data_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlink',
            name='data_label',
        ),
    ]
