# Generated by Django 5.1.2 on 2025-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0010_summarystatistic_record_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='state',
            field=models.CharField(choices=[('requestor_open', 'Requestor Open'), ('owner_open', 'Owner Open'), ('accepted', 'Accepted'), ('archived', 'Archived'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='requestor_open', max_length=50),
        ),
    ]
