# Generated by Django 5.1.2 on 2024-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0011_remove_nlink_data_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlink',
            name='negotiation_status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
