# Generated by Django 5.1.2 on 2025-08-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0011_alter_negotiation_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['archived_timestamp']},
        ),
        migrations.AddField(
            model_name='archive',
            name='change_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='changed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='owner_responses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='requestor_responses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='state',
            field=models.CharField(blank=True, choices=[('requestor_open', 'Requestor Open'), ('owner_open', 'Owner Open'), ('accepted', 'Accepted'), ('archived', 'Archived'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='negotiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='drt.negotiation'),
        ),
    ]
