# Generated by Django 5.1.2 on 2024-10-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0012_nlink_negotiation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='owner_responses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='requestor_responses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
