# Generated by Django 5.1.2 on 2024-10-21 15:46

import drt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0013_alter_negotiation_owner_responses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='negotiation_id',
            new_name='negotiation',
        ),
        migrations.RenameField(
            model_name='nlink',
            old_name='negotiation_id',
            new_name='negotiation',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='negotiation_status',
        ),
        migrations.RemoveField(
            model_name='nlink',
            name='negotiation_status',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='state',
            field=models.CharField(choices=[('requestor_open', 'Requestor Open'), ('owner_open', 'Owner Open'), ('completed', 'Completed'), ('archived', 'Archived'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='requestor_open', max_length=50),
        ),
        migrations.AlterField(
            model_name='nlink',
            name='expiration_date',
            field=models.DateTimeField(default=drt.models.default_expiration_date),
        ),
        migrations.AlterField(
            model_name='requestor',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatistics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
