# Generated by Django 5.1.2 on 2024-10-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0014_rename_negotiation_id_archive_negotiation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestor',
            name='otp_expiry',
        ),
    ]
