# Generated by Django 5.1.2 on 2024-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0015_remove_requestor_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestor',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
