# Generated by Django 5.1.2 on 2024-10-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0016_requestor_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlink',
            name='questionnaire_SAID',
        ),
        migrations.AlterField(
            model_name='nlink',
            name='negotiation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation'),
        ),
    ]
