# Generated by Django 5.1.2 on 2024-10-22 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0017_remove_nlink_questionnaire_said_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='negotiation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation'),
        ),
        migrations.AlterField(
            model_name='summarystatistics',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.nlink'),
        ),
    ]
