# Generated by Django 5.1.2 on 2024-10-23 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0018_negotiation_archived_alter_archive_negotiation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystatistics',
            name='owner_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation'),
        ),
    ]
