# Generated by Django 5.1.2 on 2024-10-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0019_alter_summarystatistics_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystatistics',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.nlink'),
        ),
    ]
