# Generated by Django 5.1.2 on 2024-10-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0020_alter_summarystatistics_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlink',
            name='state',
        ),
    ]
