# Generated by Django 5.1.2 on 2024-10-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0021_remove_nlink_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SummaryStatistics',
            new_name='SummaryStatistic',
        ),
    ]
