# Generated by Django 5.1.2 on 2024-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0022_rename_summarystatistics_summarystatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='questionnaire_SAID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
