# Generated by Django 5.1.2 on 2024-10-10 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('negotiation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NLink',
            fields=[
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('requestor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.negotiation')),
            ],
        ),
        migrations.AddField(
            model_name='negotiation',
            name='nlink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.nlink'),
        ),
        migrations.AddField(
            model_name='nlink',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.owner'),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaire_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema', models.JSONField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('saved_data', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.owner')),
            ],
        ),
        migrations.AddField(
            model_name='nlink',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.questionnaire'),
        ),
        migrations.AddField(
            model_name='nlink',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.requestor'),
        ),
        migrations.CreateModel(
            name='SummaryStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_count', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drt.owner')),
            ],
        ),
    ]
