# Generated by Django 5.1.2 on 2024-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
