services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    labels:
      - drt_backend
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - path: local.env
        required: false
      - path: .env
        required: false
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - postgres
  
  # frontend:
  #   build:
  #     context: ./drt_frontend
  #     dockerfile: ./docker/frontend.Dockerfile
  #   labels:
  #     - drt_frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend

  frontend:
    build:
      context: ./drt_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 to host
    # environment:
    #   - NODE_ENV=production
    env_file:
      - ./drt_frontend/.env      
    volumes:
      - ./drt_frontend:/app
      - /app/node_modules # Prevents overwriting the node_modules in the container
    depends_on:
      - backend

  postgres:
    image: postgres:13
    env_file:
      - path: local.env
        required: false
      - path: .env
        required: false

  redis:
    image: redis:6.2.4
