services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    labels:
      - drt_backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - local.env
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./drt_frontend
      dockerfile: drt_frontend/Dockerfile
    command: npm run dev
    ports:
      - "3000:3000" 
    # environment:
    #   - NODE_ENV=production
    # env_file:
    #   - ./drt_frontend/.env      
    volumes:
      - ./drt_frontend:/app
      - /app/node_modules # Prevents overwriting the node_modules in the container
    depends_on:
      - backend

  postgres:
    image: postgres:13
    env_file:
      - local.env
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: drt-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:      