services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - path: local.env
        required: false
      - path: .env
        required: false
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - path: local.env
        required: false
      - path: .env
        required: false

  redis:
    image: redis:6.2.4
