# Generated by Django 5.1.2 on 2024-10-09 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaire_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema', models.JSONField()),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('requestor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('negotiation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('link_created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negotiations.owner')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negotiations.questionnaire')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negotiations.requestor')),
            ],
        ),
    ]
