# Generated by Django 5.1.2 on 2024-10-09 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='negotiation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
