# Generated by Django 5.1.2 on 2025-05-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='questionnaire_SAID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
