# Generated by Django 5.1.2 on 2025-05-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0004_require_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlink',
            name='negotiation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='drt.negotiation'),
        ),
    ]
