# Generated by Django 5.1.2 on 2025-05-26 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0005_alter_nlink_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlink',
            name='data_label',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nlink',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), db_index=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='summarystatistic',
            name='data_label',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='summarystatistic',
            name='tag',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
