# Generated by Django 5.1.2 on 2025-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0006_nlink_data_label_nlink_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestor',
            name='otp',
            field=models.CharField(max_length=64),
        ),
    ]
