# Generated by Django 5.1.2 on 2025-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0007_alter_requestor_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
