# Generated by Django 5.1.2 on 2025-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0008_negotiation_rationale'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlink',
            name='record_label',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
