# Generated by Django 5.1.2 on 2025-09-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0013_add_abandoned_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='state',
            field=models.CharField(blank=True, choices=[('requestor_open', 'Requestor Open'), ('owner_open', 'Owner Open'), ('accepted', 'Accepted'), ('archived', 'Archived'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('abandoned', 'Abandoned')], max_length=50, null=True),
        ),
    ]
