# Generated by Django 5.1.2 on 2026-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0017_nlink_public_label'),
    ]

    # SummaryStatistic indexes/field changes already exist in DB; update state only
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name='summarystatistic',
                    options={'ordering': ['-summary_date']},
                ),
                migrations.AlterField(
                    model_name='summarystatistic',
                    name='data_label',
                    field=models.CharField(db_index=True, default='', max_length=255),
                ),
                migrations.AlterField(
                    model_name='summarystatistic',
                    name='record_label',
                    field=models.CharField(blank=True, db_index=True, default='', max_length=255),
                ),
                migrations.AlterField(
                    model_name='summarystatistic',
                    name='summary_date',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='summarystatistic',
                    name='tag',
                    field=models.CharField(blank=True, db_index=True, max_length=64),
                ),
                migrations.AddIndex(
                    model_name='summarystatistic',
                    index=models.Index(fields=['owner_id', '-summary_date'], name='summarystat_owner_date_idx'),
                ),
                migrations.AddIndex(
                    model_name='summarystatistic',
                    index=models.Index(fields=['owner_id', 'data_label', 'tag', 'record_label'], name='summarystat_lookup_idx'),
                ),
            ],
            database_operations=[],
        ),
    ]
