# Generated by Django 5.1.2 on 2026-09-18 19:12

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class AddIndexIfPostgres(migrations.AddIndex):
    """GIN is a Postgres access method; skip on SQLite laptop runs."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('drt', '0023_add_negotiation_fulfillment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlink',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        AddIndexIfPostgres(
            model_name='nlink',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='drt_nlink_tags_gin'),
        ),
    ]
