FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

# Install Git before the build step
RUN apk add --no-cache git


# 5. Copy the entire project (excluding files in .dockerignore)
COPY . .


RUN npm run build

RUN npm prune --production


# 8. Use a lightweight Node.js image for the final stage
FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json /app/
COPY --from=builder /app/.next /app/.next
COPY --from=builder /app/public /app/public
COPY --from=builder /app/node_modules /app/node_modules

EXPOSE 3000

CMD ["npm", "start"]
